# Created by trellis-cli vcanary
# Documentation: https://roots.io/trellis/docs/vault/

vault_mysql_root_password: bqYpkhgiNkCPv8hbxJIiAQlahZDEityyNiam7D97iUAziPoCNwrTpQBxhPSowVvh
vault_wordpress_sites:
  nectardaamazonia.com.br:
    admin_password: kqDRBGPgcFN4ptvZWG94Z6kWFbdCnMdGf9hfIhE8aJmS8dY1JebmY5SLjlX83fM4
    env:
      db_password: 0gi5nqgjBjXC6Ul6gnENqZ40E7rUyOD22URVSGXXcAmxcUSvf7AOTSw03hrUgmQv
      auth_key: v6Xyq4v41tdALva9ymOtEXgGtnySOqy7gaKd1CmhLGSMnGs7SEJr8eqqj0Wvyha0
      secure_auth_key: iVxe4R6f0ZNXoW5BDgGI0DjDzWcOEc8Y7dFo901bzkLFGVR9aAZIJrSgrbRHec7d
      logged_in_key: qMrrMCX5IYg7Mw29hdet87YdlWEKa10ZZaBFpyj7fxsyXBYqrQZdSa5HGPnsbUgs
      nonce_key: jfe1M1VpfE3P2WoPn2hOY04tmWECiXErFERW2nFU0QRT2Du7Iy3fI6U1gqdFc4SK
      auth_salt: rjapOdzdwrIBSdPhwi83OlofclzQpuj5wRIDQGeAqciDIXhh09vFtTfUWBDuSAvT
      secure_auth_salt: Jvdem7J5vTwEdIvukcNCBkJViHTETqc5oGbpVS1LIbmKbMoet9RA9FlMaAzpkwtu
      logged_in_salt: jfGtcdTSSNO1RChWHLp7kKLxsnaJCL9TJVrfdGktkVDjA1K8HsctUgtYMyTPhKVh
      nonce_salt: OMtfy7hKxsNRLduPsBEb1htT7DmsfcWs3WA94EykPgIXqDOEDQgyuK3VN6XoRKJf
